### ISSUE TITLE
Error when trying to share a READ app

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/streamsx.visualization#127]
I'm following the instructions for "Sharing READ Dashboards" in the help topics. See the following output:

```
Queenies-Work-MacBook-Pro:READ.share queeniema$ meteor --version
Meteor 1.4.2.3
Queenies-Work-MacBook-Pro:READ.share queeniema$ echo $MONGO_URL
mongodb://localhost:3001/meteor
Queenies-Work-MacBook-Pro:READ.share queeniema$ ifconfig | grep inet
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	inet6 fe80::c95:2636:89c3:7fd3%en0 prefixlen 64 secured scopeid 0x4 
	inet 192.168.0.106 netmask 0xffffff00 broadcast 192.168.0.255
	inet6 fe80::800e:57ff:fecd:fcb%awdl0 prefixlen 64 scopeid 0x9 
	inet6 fe80::7eb8:b4bf:274a:89f4%utun0 prefixlen 64 scopeid 0xa 
	inet6 fe80::e552:bc71:ce16:bfb5%utun1 prefixlen 64 scopeid 0xb 
	inet6 fd3b:b70e:f009:d582:e552:bc71:ce16:bfb5 prefixlen 64 
	inet 9.80.208.29 --> 9.80.208.29 netmask 0xfffff000 
Queenies-Work-MacBook-Pro:READ.share queeniema$ meteor --port 9.80.208.29:3002
[[[[[ ~/github/streamsx.visualization/READ.share ]]]]]

=> Started proxy.                             
/Users/queeniema/.meteor/packages/ecmascript/.0.6.1.440q0m++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/queeniema/github/streamsx.visualization/READ.share/node_modules/core-js/fn/string'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1535:35)
    at readDirectory (/Users/queeniema/.meteor/packages/meteor-tool/.1.4.2_3.1g31s5n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:291:26)
    at Watcher._fireIfDirectoryChanged (/Users/queeniema/.meteor/packages/meteor-tool/.1.4.2_3.1g31s5n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:436:23)
    at /Users/queeniema/.meteor/packages/meteor-tool/.1.4.2_3.1g31s5n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:682:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/queeniema/.meteor/packages/meteor-tool/.1.4.2_3.1g31s5n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/Users/queeniema/.meteor/packages/meteor-tool/.1.4.2_3.1g31s5n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:671:7)
    at new Watcher (/Users/queeniema/.meteor/packages/meteor-tool/.1.4.2_3.1g31s5n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:385:10)
    at AppRunner._runOnce (/tools/runners/run-app.js:774:23)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

**Comment by sriumcp** [comment]
Ok. This is interesting... I have a streamsx.visualization folder in my user directory (OS X -- Yosemite), and I also have a streamsx.visualization folder in /tmp. When I run READ.share as per in my user space, it works. When I run it in /tmp, it throws the same error as above.

I believe this has something to do with the limits that OS X imposes on the number of open files. Could you please tell me where you're running READ.share (and also try running it in your home directory as opposed to /tmp) in case your set up is similar to the above...

**Comment by queeniema** [comment]
I originally was running it from `/Users/queeniema/github/streamsx.visualization`.

Per your suggestion, I cloned the repository into my home directory (`/Users/queeniema/streamsx.visualization`), but I'm still seeing the same error. Any other suggestions?

**Comment by sriumcp** [comment]
Sorry, my comment about the directory where you're running is a bit of noise -- please ignore.
Turns out this is a mac specific issue: https://forums.meteor.com/t/error-file-table-overflow-in-meteor-1-4-1-2/30496/4

Here's what I did ... updated my os to Sierra (you probably already have; even if you haven't don't bother). But more importantly, restarted the mac multiple times as part of that process.

My guess: please restart your mac to see if this issue goes away. I also need to add: please do a `meteor npm install` within `READ.share` before you run `meteor` within the folder.

**Comment by queeniema** [comment]
So, I restarted but that didn't help. I saw a response in the Meteor forum link you posted that led me to here: https://github.com/meteor/meteor/issues/8057. Ran the following commands and it worked! Thanks for your help!

```
$ echo kern.maxfiles=65536 | sudo tee -a /etc/sysctl.conf
$ echo kern.maxfilesperproc=65536 | sudo tee -a /etc/sysctl.conf
$ sudo sysctl -w kern.maxfiles=65536
$ sudo sysctl -w kern.maxfilesperproc=65536
$ ulimit -n 65536
```
